### ISSUE TITLE
Cant open the illum.php file in localhost ... after input the database connection 

### ISSUE THREAD

**Issue by surenkl** [mrrva/illCrawler#4]
Error: Incorrect input data. ???

**Comment by surenkl** [comment]
how to run this ./illum.php --crawler ???? pls describe the way in details pls ???

**Comment by mrrva** [comment]
1. Setup mysql database and write access data to the source file.

2.you have to add one tor domain to database. For example it can be hidden wiki.

**Comment by surenkl** [comment]
Should i open the via terminal ( php illum.php --crawler ) after the
database connection
